### ISSUE TITLE
Migration tool

### ISSUE THREAD

**Issue by rshadow** [kunitake/munin2zabbix-sender#4]
How about `munin2zabbix-migration` to load data from Munin rrd file to Zabbix?

You can use RRDs in Debian/Ubuntu:
```
sudo apt-get install librrds-perl
```

**Comment by kunitake** [comment]
Thank you for your suggestion!

Although It seems very useful, I have no plan to implement it at the moment. 

But I think you can do it any minute now. Please read following blog article.

[Importing legacy Cacti/MRTG data into Zabbix](http://blog.zabbix.com/importing-legacy-cactimrtg-data-into-zabbix/692/)

Will it helo you?

Best regards,

**Comment by rshadow** [comment]
Thanks for the link. I think the ticket can be closed.
